import { cn } from "@guide/lib/utils";
import { Link2, AlertTriangle } from "lucide-react";
import { toast } from "sonner";
import { StatusPill, nextStaffTaskStatus } from "@hub/components/StatusPill";
import { QuadrantPill } from "./QuadrantPill";
import { UserAvatar } from "./UserAvatar";
import { quadrantOf, type Quadrant } from "../lib/eisenhower";
import { dueRingClass, formatDueChip, QUADRANT_DOT_CLASS } from "../lib/color";
import { useUpdateStaffTask, type StaffTask } from "../hooks/use-task-queries";

/** Cut at the last word boundary inside `max` so we never split a word. */
function smartCut(s: string, max: number): string {
  if (!s) return "";
  const t = s.trim();
  if (t.length <= max) return t;
  const head = t.slice(0, max + 1);
  const lastSpace = head.lastIndexOf(" ");
  return (lastSpace > 6 ? head.slice(0, lastSpace) : head.slice(0, max)).trim();
}

// Eisenhower cycle. Each quadrant maps to a representative (urgency, importance)
// pair that's plainly inside that quadrant — clicking the pill repeatedly walks
// these four points around the matrix.
const QUAD_ORDER: Quadrant[] = ["do", "schedule", "delegate", "drop"];
const QUAD_SCORES: Record<Quadrant, { urgency: number; importance: number }> = {
  do:       { urgency: 4, importance: 4 },
  schedule: { urgency: 2, importance: 4 },
  delegate: { urgency: 4, importance: 2 },
  drop:     { urgency: 2, importance: 2 },
};

interface TaskTileProps {
  task:          StaffTask;
  assigneeName:  string;
  onClick:       () => void;
  /**
   * Compact horizontal variant used inside the bottom dock.
   * Full tile variant used in the dashboard tile grid.
   */
  variant?:      "tile" | "dock";
  className?:    string;
}

export function TaskTile({ task, assigneeName, onClick, variant = "tile", className }: TaskTileProps) {
  const quad     = quadrantOf(task.urgency, task.importance);
  const ringCls  = dueRingClass(task.due_date);
  const unscored = task.urgency == null || task.importance == null;
  const { mutateAsync: updateTask } = useUpdateStaffTask();

  async function cycleQuadrant(e: React.MouseEvent | React.KeyboardEvent) {
    e.stopPropagation();
    e.preventDefault();
    const next   = QUAD_ORDER[(QUAD_ORDER.indexOf(quad) + 1) % QUAD_ORDER.length];
    const scores = QUAD_SCORES[next];
    try { await updateTask({ id: task.id, urgency: scores.urgency, importance: scores.importance }); }
    catch { toast.error("Failed to change quadrant"); }
  }

  async function cycleStage(e: React.MouseEvent | React.KeyboardEvent) {
    e.stopPropagation();
    e.preventDefault();
    if (task.status === "blocked") {
      toast.error("Blocked — resolve the blocker first");
      return;
    }
    try { await updateTask({ id: task.id, status: nextStaffTaskStatus(task.status) }); }
    catch { toast.error("Failed to change stage"); }
  }

  if (variant === "dock") {
    // ai_summary is generated by generate-task-summary edge function to fit
    // here without truncation. Until it lands, fall back to the title cut at
    // the last word boundary inside 22 chars so we never break mid-word.
    const label = task.ai_summary?.trim() || smartCut(task.title, 22);
    return (
      <button
        onClick={onClick}
        title={task.title}
        className={cn(
          "group flex items-center gap-2 h-9 px-3 rounded-md shrink-0",
          "border border-border/60 bg-[var(--bg-elevated)]",
          "hover:border-border transition-colors text-left",
          ringCls,
          className,
        )}
      >
        <span className={cn("w-2 h-2 rounded-full shrink-0", QUADRANT_DOT_CLASS[quad])} />
        <span className="text-xs text-foreground/90 whitespace-nowrap">{label}</span>
        {task.due_date && (
          <span className="font-mono tabular-nums text-[10px] text-muted-foreground shrink-0">
            {formatDueChip(task.due_date)}
          </span>
        )}
      </button>
    );
  }

  // Tile variant uses `role="button"` div so we can nest real <button>
  // pills inside without invalid button-in-button HTML. The pills cycle
  // their own state and stopPropagation so the parent click (open drawer)
  // doesn't also fire.
  return (
    <div
      role="button"
      tabIndex={0}
      onClick={onClick}
      onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onClick(); } }}
      className={cn(
        "group w-full text-left rounded-lg border bg-[var(--bg-elevated)] cursor-pointer",
        "p-3 space-y-2 hover:border-border transition-colors",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1",
        ringCls,
        className,
      )}
    >
      {/* Title row */}
      <div className="flex items-start gap-2">
        <span className="text-sm font-medium flex-1 leading-snug line-clamp-2">{task.title}</span>
        <button
          type="button"
          onClick={cycleQuadrant}
          onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") cycleQuadrant(e); }}
          title="Click to cycle quadrant"
          className="rounded-full hover:ring-2 hover:ring-ring/40 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          <QuadrantPill quadrant={quad} size="sm" />
        </button>
      </div>

      {/* Description preview */}
      {task.description && (
        <p className="text-xs text-muted-foreground line-clamp-2">{task.description}</p>
      )}

      {/* Footer */}
      <div className="flex items-center justify-between gap-2 pt-1">
        <div className="flex items-center gap-1.5 min-w-0">
          <UserAvatar name={assigneeName} size="xs" />
          <span className="text-[11px] text-muted-foreground truncate">{assigneeName}</span>
        </div>
        <div className="flex items-center gap-1.5 shrink-0">
          {unscored && <AlertTriangle className="w-3 h-3 text-amber-400" />}
          {task.blocked_by_task_id && task.status === "blocked" && <Link2 className="w-3 h-3 text-amber-400" />}
          {task.due_date && (
            <span className="font-mono tabular-nums text-[10px] text-muted-foreground">
              {formatDueChip(task.due_date)}
            </span>
          )}
          <button
            type="button"
            onClick={cycleStage}
            onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") cycleStage(e); }}
            title="Click to cycle stage"
            className="rounded-full hover:ring-2 hover:ring-ring/40 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            <StatusPill status={task.status} staff size="sm" />
          </button>
        </div>
      </div>
    </div>
  );
}
