-- ─────────────────────────────────────────────────────────────────────────────
-- Daily Focus Digest cron (pg_cron + pg_net)
--
-- NOTE: the cron jobs were applied directly to the database on 2026-06-09
-- (jobs `daily-focus-morning` @ '0 22 * * *' UTC = 8am AEST, and
--  `daily-focus-afternoon` @ '0 5 * * *' UTC = 3pm AEST, both ACTIVE).
-- This migration is intentionally a no-op so replays neither fail nor
-- re-create jobs, and so no service-role key lives in the repo.
--
-- To (re)create the jobs, run the following in the SQL editor, substituting
-- the service-role key from the dashboard (Settings → API). Use distinct
-- dollar-quote tags ($cmd$) — nesting plain $$ inside a DO $$ block is a
-- syntax error.
--
--   CREATE EXTENSION IF NOT EXISTS pg_cron;
--   CREATE EXTENSION IF NOT EXISTS pg_net;
--   DO $job$
--   DECLARE
--     base_url text := 'https://<PROJECT_REF>.supabase.co/functions/v1';
--     headers  jsonb := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'Authorization', 'Bearer ' || '<SERVICE_ROLE_KEY>');
--   BEGIN
--     BEGIN PERFORM cron.unschedule('daily-focus-morning');   EXCEPTION WHEN OTHERS THEN NULL; END;
--     BEGIN PERFORM cron.unschedule('daily-focus-afternoon'); EXCEPTION WHEN OTHERS THEN NULL; END;
--     PERFORM cron.schedule('daily-focus-morning', '0 22 * * *',
--       format($cmd$SELECT net.http_post(url := %L, headers := %L::jsonb, body := '{}'::jsonb)$cmd$,
--              base_url || '/daily-focus-digest', headers));
--     PERFORM cron.schedule('daily-focus-afternoon', '0 5 * * *',
--       format($cmd$SELECT net.http_post(url := %L, headers := %L::jsonb, body := '{}'::jsonb)$cmd$,
--              base_url || '/daily-focus-digest', headers));
--   END $job$;
-- ─────────────────────────────────────────────────────────────────────────────
SELECT 1; -- no-op
